# Generated by Django 2.0.3 on 2018-03-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('San Lorenzo', 'San Lorenzo'), ('Fernando de la Mora', 'Fernando de la Mora'), ('Asuncion', 'Asuncion')], max_length=20)),
                ('country', models.CharField(choices=[('PRY', 'Paraguay'), ('BRZ', 'Brazil'), ('ARG', 'Argentina')], max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('activity_type', models.CharField(choices=[('reforestacion', 'Reforestacion'), ('cuenca_acuifera', 'Cuenca Acuifera'), ('otros', 'Otros')], max_length=20)),
                ('preference_zone', models.CharField(choices=[('oriental', 'Oriental'), ('occidental', 'Occidental'), ('otras_sugerencias', 'Otras sugerencias')], max_length=20)),
                ('size', models.CharField(choices=[('1-500', '1 - 500 Hect.'), ('500-1000', '500 - 1000 Hect.'), ('1000-3000', '1000 - 3000 Hect.')], max_length=20)),
                ('budget', models.CharField(choices=[('0-1.000.000', '0 - 1.000.000 USD'), ('1.000.000-3.000.000', '1.000.000 - 3.000.000 USD'), ('3.000.000-6.000.000', '3.000.000 - 6.000.000 USD')], max_length=30)),
            ],
        ),
    ]
