# Generated by Django 2.0.3 on 2018-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateField(auto_now_add=True)),
                ('cantidad_consultas', models.IntegerField()),
            ],
        ),
    ]
